// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz9oETBwcUjab28EF8g94I9KJ8-FnD_g8',
    appId: '1:687228699331:web:f23771ea54e78605601876',
    messagingSenderId: '687228699331',
    projectId: 'student-lms-5740d',
    authDomain: 'student-lms-5740d.firebaseapp.com',
    databaseURL: 'https://student-lms-5740d-default-rtdb.firebaseio.com',
    storageBucket: 'student-lms-5740d.appspot.com',
    measurementId: 'G-L92DSSLHK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2fCg96eEnRqx2JFAYia6Phg-U--awry4',
    appId: '1:687228699331:android:b4422de7071e9e8c601876',
    messagingSenderId: '687228699331',
    projectId: 'student-lms-5740d',
    databaseURL: 'https://student-lms-5740d-default-rtdb.firebaseio.com',
    storageBucket: 'student-lms-5740d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMwtm_CebgG-Ul3thY9ED4Kf_tT8ghbOk',
    appId: '1:687228699331:ios:78301711edad97b2601876',
    messagingSenderId: '687228699331',
    projectId: 'student-lms-5740d',
    databaseURL: 'https://student-lms-5740d-default-rtdb.firebaseio.com',
    storageBucket: 'student-lms-5740d.appspot.com',
    iosClientId: '687228699331-848t4h4s6sc5ufn1mi7ao8hh6uoq0ji7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterMyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMwtm_CebgG-Ul3thY9ED4Kf_tT8ghbOk',
    appId: '1:687228699331:ios:78301711edad97b2601876',
    messagingSenderId: '687228699331',
    projectId: 'student-lms-5740d',
    databaseURL: 'https://student-lms-5740d-default-rtdb.firebaseio.com',
    storageBucket: 'student-lms-5740d.appspot.com',
    iosClientId: '687228699331-848t4h4s6sc5ufn1mi7ao8hh6uoq0ji7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterMyapp',
  );
}
